// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.Stub.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\TestSupportTools_0_3\AutoTestPrep\dev\src\StubCodeGenerator\Template\StubSourceTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class StubSourceTemplate : StubTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 7 "E:\development\TestSupportTools_0_3\AutoTestPrep\dev\src\StubCodeGenerator\Template\StubSourceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateStdHeaderInclude(Config.StandardHeaderFiles)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 8 "E:\development\TestSupportTools_0_3\AutoTestPrep\dev\src\StubCodeGenerator\Template\StubSourceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateUserHeaderInclude(Config.UserHeaderFiles)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 9 "E:\development\TestSupportTools_0_3\AutoTestPrep\dev\src\StubCodeGenerator\Template\StubSourceTemplate.tt"

	if (null != this.ParentFunction.SubFunctions) {
		foreach (var subFunction in this.ParentFunction.SubFunctions) {

            
            #line default
            #line hidden
            
            #line 13 "E:\development\TestSupportTools_0_3\AutoTestPrep\dev\src\StubCodeGenerator\Template\StubSourceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.CreateStubBody(subFunction)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 14 "E:\development\TestSupportTools_0_3\AutoTestPrep\dev\src\StubCodeGenerator\Template\StubSourceTemplate.tt"
	
		}
	}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
