// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutoTestPrep.Model.Tempaltes.Stub
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using AutoTestPrep.Model.InputInfos;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Stub\TestStubTemplate_Base.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class TestStubTemplate_Base : TestStubTemplate_BaseBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            return this.GenerationEnvironment.ToString();
        }
        
        #line 7 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Stub\TestStubTemplate_Base.tt"

	//Property for stub templates.

	/// <summary>
	/// Function information.
	/// </summary>
	protected Function ParentFunction;

	/// <summary>
	/// Sub function information
	/// </summary>
	protected Function SubFunction;

	/// <summary>
	/// Test data information.
	/// </summary>
	protected TestDataInfo TestDataInfo;

        
        #line default
        #line hidden
        
        #line 25 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Stub\TestStubTemplate_Base.tt"

	//Common method to create name of variables used in stub files.
	
	/// <summary>
	/// Create "called count" variable name.
	/// </summary>
	/// <returns>"called count" variable name.</returns>
	protected virtual string CreateFunctionCalledCountBufferName()
	{
		string calledCountVariableName = this.SubFunction.Name + "_called_count";
		return calledCountVariableName;
	}

	protected virtual string CreateArgumentBufferVariableName(Parameter argument)
	{
		string variableArgumentBufferName = $"{this.SubFunction.Name}_{argument.Name}";
		return variableArgumentBufferName;
	}

	/// <summary>
	/// Create "function return" buffer name.
	/// </summary>
	/// <returns>"Function return" buffer name.</returns>
	protected virtual string CreateFunctionReturnBufferName()
	{
		string functionReturnBufferName = string.Empty;
		functionReturnBufferName = $"{this.SubFunction.Name}_return_value";
		return functionReturnBufferName;
	}

	/// <summary>
	/// Create "argument output buffer" name.
	/// </summary>
	/// <param name="argument">Argument information.</param>
	/// <returns>"Argument output buffer" name.</returns>
	protected virtual string CreateOutputBufferName(Parameter argument)
	{
		string variableName = string.Empty;
		variableName = $"{CreateArgumentBufferVariableName(argument)}_value";
		return variableName;
	}

        
        #line default
        #line hidden
        
        #line 67 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Stub\TestStubTemplate_Base.tt"

	//Common and base metods to create code for stub files.

	/// <summary>
	/// Create code declaring variable to set the count the function called.
	/// </summary>
	/// <param name="function">Function information</param>
	/// <returns>Code to declare variable to set the count function called.</returns>
	protected virtual string CreateFunctionCalledCountBufferDecalre()
	{
		string calledCountBufferName = string.Empty;
		calledCountBufferName = "int ";
		calledCountBufferName += this.CreateFunctionCalledCountBufferName();
		return calledCountBufferName;
	}

	/// <summary>
	/// Create buffer name to store value a stub should return.
	/// </summary>
	/// <param name="function">Function data of stub.</param>
	/// <returns>Buffer name.
	/// It is in format below:
	/// (Function_ActualDataType) (FunctionName)_return_value.
	/// </returns>
	protected virtual string CreateFunctionReturnBufferDeclare()
	{
		string returnBufferName = string.Empty;
		if (ParentFunction.HasReturn())
		{
			returnBufferName = this.SubFunction.ActualDataType();
			returnBufferName += " ";
			returnBufferName += $"{CreateFunctionReturnBufferName()}";
		}
		return returnBufferName;
	}

	/// <summary>
	/// Create code to declare buffer to store argument.
	/// </summary>
	/// <param name="argument">Parameter object of argument.</param>
	/// <returns>Code to declare buffer to store arugument.
	///	It is in format below:
	///	(ArgumentDataType) (FunctionName)_(ArgumentName)
	/// </returns>
	protected virtual string CreateFunctionArgumentBufferDeclare(Parameter argument)
	{
		string argumentBufferDeclare = string.Empty;
		argumentBufferDeclare = argument.ActualDataType();
		argumentBufferDeclare += " ";
		argumentBufferDeclare += CreateArgumentBufferVariableName(argument);
		return argumentBufferDeclare;
	}

	/// <summary>
	/// Creat code to declare buffer to store output value.
	/// </summary>
	/// <param name="function">Function information.</param>
	/// <param name="argument">Argument information.</param>
	/// <returns>Create code to store value to return via pointer.</returns>
	protected virtual string CreateFunctionOutputBufferDeclare(Parameter argument)
	{
		string outputBufferDeclare = string.Empty;

		if ((1 == argument.PointerNum) ||
			(2 == argument.PointerNum))
		{
			if ((argument.Mode == Parameter.AccessMode.Out) ||
				(argument.Mode == Parameter.AccessMode.Both))
			{
				outputBufferDeclare = argument.DataType;
				outputBufferDeclare += " ";
				outputBufferDeclare += $"{this.SubFunction.Name}_{argument.Name}";
				outputBufferDeclare += "_value";
			}
			else
			{
				throw new ArgumentException();
			}
		}
		else
		{
			throw new ArgumentException();
		}
		return outputBufferDeclare;
	}

	/// <summary>
	/// Create code of function entry point to initialize 
	/// </summary>
	/// <returns>Code to declare function entry point to initialize buffer parameter.</returns>
	protected virtual string CreateBufferInitializeFunction()
	{
		string bufferInitializeFunction = string.Empty;
		bufferInitializeFunction = "void ";
		bufferInitializeFunction += this.SubFunction.Name;
		bufferInitializeFunction += "_init()";

		return bufferInitializeFunction;
	}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class TestStubTemplate_BaseBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
