// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutoTestPrep.Model.Tempaltes.Stub
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Stub\TestStubTemplate_Header.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class TestStubTemplate_Header : TestStubTemplate_Base
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("#pragma once\r\n//Sub function called count.\r\n");
            
            #line 9 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Stub\TestStubTemplate_Header.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateFunctionCalledCountBufferDecalre(SubFunction)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 10 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Stub\TestStubTemplate_Header.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateFunctionReturnBufferDeclare(SubFunction)));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n//Argument buffer.\r\n");
            
            #line 13 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Stub\TestStubTemplate_Header.tt"
 foreach (var argumentItem in SubFunction.Arguments) { 
            
            #line default
            #line hidden
            
            #line 14 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Stub\TestStubTemplate_Header.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateFunctionArgumentBufferDeclare(SubFunction, argumentItem)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 15 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Stub\TestStubTemplate_Header.tt"
	}	
            
            #line default
            #line hidden
            this.Write("//Return value buffer\r\n");
            
            #line 17 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Stub\TestStubTemplate_Header.tt"
 foreach (var argumentItem in SubFunction.Arguments) { 
            
            #line default
            #line hidden
            
            #line 18 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Stub\TestStubTemplate_Header.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateFunctionOutputBufferDeclare(SubFunction, argumentItem)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 19 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Stub\TestStubTemplate_Header.tt"
	}	
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 20 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Stub\TestStubTemplate_Header.tt"

	/// <summary>
	/// Create code declaring variable to set the count the function called.
	/// </summary>
	/// <param name="function">Function information</param>
	/// <returns>Code to declare variable to set the count function called.</returns>
	protected override string CreateFunctionCalledCountBufferDecalre(Function function)
	{
		string calledCountBufferName = base.CreateFunctionCalledCountBufferDecalre(function);
		calledCountBufferName = "extern " + calledCountBufferName;
		calledCountBufferName += ";";
		return calledCountBufferName;
	}

	protected override string CreateFunctionReturnBufferDeclare(Function function)
	{
		string returnBufferName = base.CreateFunctionReturnBufferDeclare(function);
		if (!(string.IsNullOrEmpty(returnBufferName))) {
			returnBufferName = "extern " + returnBufferName;
			returnBufferName += "[];";
		}
		return returnBufferName;
	}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
