// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.TestDriver.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\TestSupportTools_0_2_0\AutoTestPrep\dev\src\MinUnitDriverCodeGenerator\Template\MinUnitSourceSetUpTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class MinUnitSourceSetUpTemplate : MinUnitTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("//Initialize test stub buffers.\r\nvoid ");
            
            #line 8 "E:\development\TestSupportTools_0_2_0\AutoTestPrep\dev\src\MinUnitDriverCodeGenerator\Template\MinUnitSourceSetUpTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateStubInitMethodName(this.TargetFunction)));
            
            #line default
            #line hidden
            this.Write("()\r\n{\r\n");
            
            #line 10 "E:\development\TestSupportTools_0_2_0\AutoTestPrep\dev\src\MinUnitDriverCodeGenerator\Template\MinUnitSourceSetUpTemplate.tt"
	if (null != this.TargetFunction.SubFunctions) {	
            
            #line default
            #line hidden
            
            #line 11 "E:\development\TestSupportTools_0_2_0\AutoTestPrep\dev\src\MinUnitDriverCodeGenerator\Template\MinUnitSourceSetUpTemplate.tt"
		foreach (var subFunction in this.TargetFunction.SubFunctions) {	
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 12 "E:\development\TestSupportTools_0_2_0\AutoTestPrep\dev\src\MinUnitDriverCodeGenerator\Template\MinUnitSourceSetUpTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.CreateStubInitializeMethodName(subFunction)));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 13 "E:\development\TestSupportTools_0_2_0\AutoTestPrep\dev\src\MinUnitDriverCodeGenerator\Template\MinUnitSourceSetUpTemplate.tt"
		}	
            
            #line default
            #line hidden
            
            #line 14 "E:\development\TestSupportTools_0_2_0\AutoTestPrep\dev\src\MinUnitDriverCodeGenerator\Template\MinUnitSourceSetUpTemplate.tt"
	}	
            
            #line default
            #line hidden
            this.Write("}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
