// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutoTestPrep.Model.Tempaltes.Driver.mid_unit
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using AutoTestPrep.Model.Tempaltes.Driver.min_unit;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class TestDriverTemplate_mid_unit_Source : TestDriverTemplate_min_unit_Source
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("/*\r\n *\t");
            
            #line 9 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TargetFunction.Name));
            
            #line default
            #line hidden
            this.Write(" test driver source code using mid_unit unit test framework.\r\n */\r\n");
            
            #line 11 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"

	foreach (var headerFile in this.TestDataInfo.DriverIncludeStandardHeaderFiles) {
		if ((!(string.IsNullOrEmpty(headerFile))) && (!(string.IsNullOrWhiteSpace(headerFile)))) {

            
            #line default
            #line hidden
            this.Write("#include <");
            
            #line 15 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(headerFile));
            
            #line default
            #line hidden
            this.Write(">\r\n");
            
            #line 16 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"
		
		}
	}

            
            #line default
            #line hidden
            
            #line 20 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"

	foreach (var headerFile in this.TestDataInfo.DriverIncludeUserHeaderFiles) {
		if ((!(string.IsNullOrEmpty(headerFile))) && (!(string.IsNullOrWhiteSpace(headerFile)))) {

            
            #line default
            #line hidden
            this.Write("#include \"");
            
            #line 24 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(headerFile));
            
            #line default
            #line hidden
            this.Write("\"\r\n");
            
            #line 25 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"
		}
	}

            
            #line default
            #line hidden
            
            #line 28 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"

	//Include header files about stub of sub functions.
	if ((null != this.SubFunctions) &&
		(0 < this.SubFunctions.Count()))
	{
		foreach (var subFunctionItem in this.SubFunctions) {

            
            #line default
            #line hidden
            this.Write("#include \"");
            
            #line 35 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateStubHeaderIncludeCode(subFunctionItem)));
            
            #line default
            #line hidden
            this.Write("\"\r\n");
            
            #line 36 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"

		}
	}

            
            #line default
            #line hidden
            this.Write("#include \"mid_unit.h\"\r\n\r\n//Test target function\r\n");
            
            #line 43 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TargetFunction.ToString()));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n//Initialize test stub buffers.\r\n");
            
            #line 46 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateSetupMethodEntryPointCode()));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 48 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"

	if ((null != this.SubFunctions) &&
		(0 < this.SubFunctions.Count()))
	{
		foreach (var subFunctionItem in this.SubFunctions) {

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 54 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateBufferInitializeFunctionName(subFunctionItem)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 55 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"

		}
	}

            
            #line default
            #line hidden
            this.Write("}\r\n\r\n//Test method.\r\n");
            
            #line 62 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"
 foreach (var testCase in this.Test.TestCases) {	
            
            #line default
            #line hidden
            this.Write("static char* ");
            
            #line 63 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.CreateTestCaseMethodName(testCase)));
            
            #line default
            #line hidden
            this.Write("()\r\n{\r\n\t//Declare argument.\r\n");
            
            #line 66 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"

	if ((null != this.TargetFunction.Arguments) && (0 < this.TargetFunction.Arguments.Count())) {
		foreach (var argumentItem in this.TargetFunction.Arguments) {

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 70 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateCodeToDeclareArgument(argumentItem)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 71 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"
		}	
	
	}

            
            #line default
            #line hidden
            this.Write("\r\n\t//Setup test values.\r\n");
            
            #line 77 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"
	if ((null != testCase.Input) && (0 < testCase.Input.Count())) {
		foreach (var inputItem in testCase.Input) {

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 80 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateCodeToSetUpTestParameter(inputItem)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 81 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"

		}
	}

            
            #line default
            #line hidden
            this.Write("\r\n\t//Call target function\r\n\t");
            
            #line 87 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateCodeToCallTargetFunction()));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n\t//Check output and expects.\r\n");
            
            #line 90 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"

	if ((null != testCase.Expects) &&
		(0 < testCase.Expects.Count()))
	{
		foreach (var expectItem in testCase.Expects)
		{

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 97 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateCodeToCheckOutputAndExpect(expectItem)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 98 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"

		}
	}

            
            #line default
            #line hidden
            this.Write("\r\n\treturn 0;\r\n}\r\n\r\n");
            
            #line 106 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"
	}	//End of top "foreach" scope. 
            
            #line default
            #line hidden
            this.Write("\r\n//Method to call all test case method.\r\nchar* ");
            
            #line 109 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateRunTestMethodEntryPoint()));
            
            #line default
            #line hidden
            this.Write("()\r\n{\r\n");
            
            #line 111 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"
 foreach (var testCase in this.Test.TestCases) {	
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 112 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CreateCodeToCallTestRunMethod(testCase)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 113 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\mid_unit\TestDriverTemplate_mid_unit_Source.tt"
 }	//End of "foreach" scope. 
            
            #line default
            #line hidden
            this.Write("\r\n\treturn 0;\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
