// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutoTestPrep.Model.Tempaltes.Driver.min_unit
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using AutoTestPrep.Model.InputInfos;
    using AutoTestPrep.Model.Tempaltes.Driver.common;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\min_unit\TestDriverTemplate_min_unit_Base.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class TestDriverTemplate_min_unit_Base : TestDriverTemplateCommonBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            return this.GenerationEnvironment.ToString();
        }
        
        #line 9 "E:\development\TestSupportTools\AutoTestPrep\dev\src\AutoTestPrep\Model\Tempaltes\Driver\min_unit\TestDriverTemplate_min_unit_Base.tt"



        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
